---
title: "Fall Semester Goals"
author: "Emily Hamp"
date: "2026-08-25"
categories: [goals, daily-entries]
description: "Fall 2026 Goals"
image: ""
---

# Overview

Fall 2026 goals

## Goals

- [ ] Survive the MCAT
- [ ] Develop a strong background in ciliate biology and the molecular basis of adaptation
- [ ] Begin analysis of genome rearrangment in *Loxodes*
- [ ] Design experiments for studying adaptation in *Tetrahymena thermophilia*

### Writing and Manuscripts 

- [ ] Read primary literature on the molecular basis of adaptation and ciliate biology 
- [ ] Maintain annotated bibliography

### Analysis and Benchwork

- [ ] Analyze existing *Loxodes* data to examine germline-soma genome rearrangement and structure
- [ ] Maintain *Tetrahymena thermophila* cultures 
- [ ] Develop methods for measuring phenotypic responses in *T. thermophilia*, including growth rate, cell morphometrics, swimming behavior, and mating 
- [ ] Develop methods for measuring molecular changes via RNA sequencing, single nucleotide polymorphisms (SNPs), and copy number variation (CNV) and look for structural rearrangements 

### Funding

### Other

- [ ] Regularly update digital lab notebook

# Primary Skill Building

- [ ] Develop proficiency in ciliate terminology 
- [ ] Develop proficiency in bioinformatic analysis of genome rearrangement
- [ ] Develop proficiency in *Tetrahymena* culture, microscopy, and phenotypic measurements 
